### ISSUE TITLE
Compile errors

### ISSUE THREAD

**Issue by diorn** [Leonidas300/steamshortcutmaker#2]
And getting this when trying to compile the source

`mainwindow.cpp:167:35: warning: unused parameter ‘index’ [-Wunused-parameter]
  167 | void MainWindow::indexChanged(int index)
      |                               ~~~~^~~~~
make: *** No rule to make target 'ShortCutMaker.png', needed by 'qrc_res.cpp'.  Stop.
`

**Comment by Leonidas300** [comment]
Hi,
Could you tell me how exactly did you do it? I mean, did you open project with QTCreator and then build it?

**Comment by diorn** [comment]
Hello,
No i was just trying to compile it from the terminal after installing qt creator as per this guide:
https://vitux.com/compiling-your-first-qt-program-in-ubuntu/

**Comment by Leonidas300** [comment]
Ok. I found what was causing this error. I uploaded one additional file. Compiler could not find the file ShortCutMaker.png but in project directory was ShortcutMaker.png. If you download this project again or rename the file from ShortcutMaker.png => ShortCutMaker.png it should work now without a problem :-)
